name: Build disk images

on:
  workflow_run:
    workflows:
      - Build container images
    types:
      - completed
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.base }}:${{ matrix.stream }} (${{ matrix.disk-type }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        disk-type: [qcow2, anaconda-iso]
        base:
          - bazzite-howdy
          - bazzite-dx-howdy
          - bazzite-dx-nvidia-howdy
          - bazzite-dx-nvidia-gnome-howdy
          - bluefin-howdy
          - bluefin-dx-howdy
          - bluefin-nvidia-howdy
          - bluefin-dx-nvidia-open-howdy
        stream: [gts, stable]
        exclude:
          - base: bazzite-howdy
            stream: gts
          - base: bazzite-dx-howdy
            stream: gts
          - base: bazzite-dx-nvidia-howdy
            stream: gts
          - base: bazzite-dx-nvidia-gnome-howdy
            stream: gts

    permissions:
      contents: read
      packages: read
      id-token: write

    env:
      IMAGE_NAME: ${{ matrix.base }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      DEFAULT_TAG: ${{ matrix.stream }}
      BIB_IMAGE: ghcr.io/lorbuschris/bootc-image-builder:20250608

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Prepare env and pick desktop
        id: prep
        shell: bash
        run: |
          set -euo pipefail
          # derive display manager from base name
          base="${{ matrix.base }}"
          dm="gnome"
          if [[ "$base" == bazzite* && "$base" != *gnome* ]]; then
            dm="kde"
          fi
          echo "DISPLAY_MANAGER=$dm" >> "$GITHUB_ENV"

          # normalize registry/name for image param
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> "$GITHUB_ENV"
          echo "IMAGE_NAME=${IMAGE_NAME,,}"         >> "$GITHUB_ENV"

          # pick correct config for type
          if [[ "${{ matrix.disk-type }}" == "anaconda-iso" ]]; then
            echo "CONFIG_FILE=./disk_config/iso-${dm}.toml" >> "$GITHUB_ENV"
          else
            echo "CONFIG_FILE=./disk_config/disk.toml" >> "$GITHUB_ENV"
          fi

          # record user ids for chown
          echo "USER_UID=$(id -u)" >> "$GITHUB_ENV"
          echo "USER_GID=$(id -g)" >> "$GITHUB_ENV"

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false

      - name: Maximize build space (x64 only)
        if: runner.arch == 'X64'
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e
        with:
          remove-codeql: true

      - name: Build disk images
        id: build
        uses: osbuild/bootc-image-builder-action@main
        with:
          builder-image: ${{ env.BIB_IMAGE }}
          config-file: ${{ env.CONFIG_FILE }}
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}
          chown: ${{ env.USER_UID }}:${{ env.USER_GID }}
          types: ${{ matrix.disk-type }}
          additional-args: --use-librepo=True
          rootfs: btrfs

      - name: Upload to S3
        shell: bash
        env:
          RCLONE_CONFIG_S3_TYPE: s3
          RCLONE_CONFIG_S3_PROVIDER: AWS
          RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_S3_REGION: us-east-1
          RCLONE_CONFIG_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          SOURCE_DIR: ${{ steps.build.outputs.output-directory }}
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
          rclone copy "$SOURCE_DIR" "S3:${{ secrets.S3_BUCKET_NAME }}/${{ matrix.base }}/${{ matrix.stream }}/${{ matrix.disk-type }}"
